### ISSUE TITLE
Update OKR tracking

### ISSUE THREAD

**Issue by rihp** [Web3-API/dao#39]
Seeing how we have about 5 more weeks before we close the Q4, it'd be a good moment to look at the OKRs we have been tracking, and hopefully focus our efforts towards these shared and time sensitive goals.

To help us all work asynchronously, I could use some guidance to have all of these OKRs correctly tracked through Github Projects or Milestones, possibly at the Web3API Organization level (https://github.com/orgs/Web3-API/projects).  

Still wrapping my head around how we can sort and organize these OKRs, since some of them overlap, and each individual task related to an OKR should be linking ultimately to an specific Issues in the correct repos.

Overview of initial roadmap we've been following so far
![image](https://user-images.githubusercontent.com/12145726/99882261-67157580-2c1f-11eb-8db6-a47c3eef08b2.png)

**Comment by rihp** [comment]
Critical Milestone/ OKR of funding 1M USD is divided in 3 tasks: Allocating Batch A, B, and C of W3API tokens.

Created #40 #41 #42 respectively

**Comment by rihp** [comment]
# Development Milestones for Q4 2020:
- [ ] First API Live -> #44
- [ ] First App Live -> #45 
- [ ] Release Pre Alpha -> #43

**Comment by rihp** [comment]
Public OKRs moved to this repo for better transparency
https://github.com/Web3-API/roadmap/
